### ISSUE TITLE
Time tracking

### ISSUE THREAD

**Issue by SamuelSlavik** [DCGM/semant-annotation#4]
- [x] Convert english 15hour system into our 24hour system
- [x] Fix clock icon
- [x] Use local time
- [ ] 

-
- Create a bar in the menu with ongoing time tracking
- Local storage ?
